name: Keep Codespace Alive

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Codespace
        run: curl -s https://lonely-werewolf-q7g5wgwg9xgxcx6jw-3000.app.github.dev/ || true
